Projects popup
Artbsc1992/My-Portfolio pull request #17
Opened 2022-04-06 21:17 UTC by Artbsc1992

# Coding partner: @Danie12345 
### Achievements.
-Build new HTML elements with javascript.
-Store data objects within an array.
-Make popup responsive and stylish.

2022-04-06 22:10 UTC, Artbsc1992 commented
Hello, @chaw-bot I had to do a last time commit sorry for that could you please review my code again?

2022-04-06 23:13 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @Artbsc1992, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Good commit messages
✔️ All linters are passing
✔️ Good PR Title and description

## Required 
- [x] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-06 23:13 UTC, sja-thedude commented on index.js
> +    },
- I have added a video below which shows that you have not added a popup for multi-post stories and links for see project and see source.

https://user-images.githubusercontent.com/70269507/162087327-c9be7230-1e91-4554-8003-81ffb6aeea63.mov

- [ ] Kindly add links to the See Live and See Source as its shows the project details you made.
- [ ] Kindly add the popup for the mobile version and desktop version for Multi Post Stories as per the Figma design given below.
- Desktop popup:
<img width="666" alt="Screenshot 2022-04-07 at 1 47 23 AM" src="https://user-images.githubusercontent.com/70269507/162087520-997c69ec-b7ba-4148-920d-5821e9bccf48.png">
- Mobile Popup:
<img width="343" alt="Screenshot 2022-04-07 at 1 45 45 AM" src="https://user-images.githubusercontent.com/70269507/162087570-488cd47e-4aab-43ed-8dab-d0bfd46fcfbc.png">

2022-04-07 03:49 UTC, Davidosky007 reviewed
Hello @Artbsc1992  👋,

_This is an additional review as a result of the second opinion request._

- Firstly i can see that all the necessary popup sections were created dynamically ( name, description, featured image, technologies, link to live version, link to source.) 
![image](https://user-images.githubusercontent.com/52497246/162115702-7fd4c55c-1a3b-43fa-a9c1-2b4b06b39eb5.png)

- Secondly, note that all see projects buttons should lead to a popup so as the reviewer requested kindly fix it 🙏 

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)

Keep rocking 🚀!

2022-04-07 03:54 UTC, Meltrust approved these changes
Hi @Artbsc1992,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-07 14:36 UTC, merged